export const FETCH_TVSHOWS_REQUEST = 'FETCH_TVSHOWS_REQUEST';
export const FETCH_TVSHOWS_SUCCESS = 'FETCH_TVSHOWS_SUCCESS';
export const FETCH_TVSHOWS_FAILURE = 'FETCH_TVSHOWS_FAILURE';
export const RESET_TVSHOWS_LIST = 'RESET_TVSHOWS_LIST';
